// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWittLaG1NKYsXNmOqQQzgB1_xpP9Ea4I',
    appId: '1:154333719617:android:beb4754234e539098aeac0',
    messagingSenderId: '154333719617',
    projectId: 'jobilee-7a95e',
    storageBucket: 'jobilee-7a95e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaOh0oV7Qzl6HMKx-zKsJXxF5gOPtrc1I',
    appId: '1:154333719617:ios:f0cf9af988f2f9a58aeac0',
    messagingSenderId: '154333719617',
    projectId: 'jobilee-7a95e',
    storageBucket: 'jobilee-7a95e.firebasestorage.app',
  );
}
